<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Consultoría de Ciberseguridad" />
        <meta name="author" content="TechSolutions" />
        <title>TechSolutions</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="index.php">TechSolutions</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="index.php">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" href="contacto.php">Contacto</a></li>
                        <li class="nav-item"><a class="nav-link" href="servicio.php">Servicios</a></li>
                        <li class="nav-item"><a class="nav-link" href="equipo.php">Equipo</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
            <!-- Heading Row-->
            <div class="row gx-4 gx-lg-5 align-items-center my-5">
                <div class="col-lg-7">
                    <img class="img-fluid rounded mb-4 mb-lg-0" src="https://media.istockphoto.com/id/1420039900/es/foto/cyber-security-ransomware-email-phishing-tecnolog%C3%ADa-cifrada-informaci%C3%B3n-digital-protegida.jpg?s=612x612&w=0&k=20&c=yaDKIPCvj7N9IYTX9IJGy4_XOose4rIDKsX5ByXWm2E=" alt="Ciberseguridad" />
                </div>
                <div class="col-lg-5">
                    <h1 class="font-weight-light">TechSolutions Te Protege</h1>
                    <p>TechSolutions Te Protege garantiza la seguridad digital de tu empresa, protegiendo tus datos más valiosos frente a las crecientes amenazas cibernéticas. Implementamos soluciones avanzadas de ciberseguridad para prevenir ataques y mitigar riesgos, manteniendo la integridad de tus sistemas en todo momento.</p>
                    <a class="btn btn-primary" href="#!">Inicia Ahora</a>
                </div>
            </div>
            <!-- Call to Action-->
            <div class="card text-white bg-secondary my-5 py-4 text-center">
                <div class="card-body">
                    <p class="text-white m-0">La seguridad de tu empresa no puede esperar. Actúa antes de que sea tarde. Con nuestras soluciones de ciberseguridad, mantén tus datos y sistemas protegidos contra cualquier amenaza. ¡Solicita una auditoría de seguridad gratuita ahora y asegura la tranquilidad de tu negocio!</p>
                </div>
            </div>
            <!-- Content Row-->
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Análisis de Vulnerabilidades</h2>
                            <p class="card-text">Identificamos los puntos débiles en tus sistemas para prevenir ataques y mejorar la seguridad de tus datos sensibles.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">Más Información</a></div>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Protección Anti-Ransomware</h2>
                            <p class="card-text">Implementamos sistemas avanzados de protección contra el ransomware para evitar secuestros de información y garantizar la continuidad de tu negocio.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">Más Información</a></div>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Cifrado de Datos</h2>
                            <p class="card-text">Protegemos tus datos mediante técnicas de cifrado avanzadas, asegurando que la información sensible no sea vulnerable ante accesos no autorizados.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">Más Información</a></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-4 px-lg-5">
                <p class="m-0 text-center text-white">Copyright &copy; TechSolutions 2024</p>
            </div>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="js/scripts.js"></script>
    </body>
</html>

